# Generated by Django 5.2.4 on 2025-07-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("names", models.CharField(max_length=255)),
                ("course", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=15)),
                ("result", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("student_id", models.CharField(max_length=15)),
            ],
        ),
    ]
